repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.54.0
    hooks:
    -   id: cfn-python-lint
        #    entry: cfn-lint --ignore-templates .pre-commit-config.yaml -t templates/nlb.yaml
        args: [-t, templates/*yaml, --debug]
-   repo: https://github.com/AleksaC/mirrors-cfn-nag
    rev: v0.6.13  # Use the sha / tag you want to point at
    hooks:
    -   id: cfn-nag
        name: cfn-nag
        description: Wrapper around cfn_nag_scan that allows it to be ran on multiple files within a single hook
        entry: cfn_nag_scan_wrapper
        language: ruby
        files: templates/
        args: [--input-path, templates/]
        pass_filenames: false
        require_serial: false
